pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.9-slim'
                }
            }
            steps {
                sh 'python -m py_compile server/main.py server/test_main.py'
            }
        }
        stage('Test') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'server'
                }
            }
            steps {
                sh '''
                        docker-compose -f server/docker-compose.yml up --build -d
                        docker-compose -f server/docker-compose.yml exec web pytest --verbose --junit-xml /test-reports/results.xml server/test_main.py
                        docker-compose -f server/docker-compose.yml down
                    '''
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}